-- ========================================
-- Test schema for clazz-lms (H2 compatible)
-- Translated from production MySQL schema, simplified for testing.
--
-- Notable adaptations for H2:
--   - INT GENERATED BY DEFAULT AS IDENTITY (H2's standard auto-increment)
--   - TIMESTAMP instead of DATETIME (better H2 compatibility)
--   - UNIQUE inlined with column definitions (cleaner)
-- ========================================

DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS clazz;
DROP TABLE IF EXISTS emp;
DROP TABLE IF EXISTS dept;

-- ========================================
-- dept (department)
-- ========================================
CREATE TABLE dept (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(10) NOT NULL UNIQUE,
    create_time TIMESTAMP DEFAULT NULL,
    update_time TIMESTAMP DEFAULT NULL
);

-- ========================================
-- emp (employee)
-- ========================================
CREATE TABLE emp (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(20) NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    gender      TINYINT NOT NULL DEFAULT 1,
    phone       CHAR(11) NOT NULL UNIQUE,
    dept_id     INT DEFAULT NULL,
    create_time TIMESTAMP DEFAULT NULL,
    update_time TIMESTAMP DEFAULT NULL
);

-- ========================================
-- operate_log (audit log written by LogAspect AOP)
-- Required because the @Log annotation on controllers triggers
-- LogAspect, which writes a row here after each annotated method.
-- Without this table, any test hitting an @Log-annotated endpoint fails.
-- ========================================
CREATE TABLE operate_log (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operate_emp_id  INT DEFAULT NULL,
    operate_time    TIMESTAMP DEFAULT NULL,
    class_name      VARCHAR(100) DEFAULT NULL,
    method_name     VARCHAR(100) DEFAULT NULL,
    method_params   VARCHAR(2000) DEFAULT NULL,
    return_value    VARCHAR(2000) DEFAULT NULL,
    cost_time       BIGINT DEFAULT NULL
);

-- ========================================
-- clazz (class)
-- ========================================
CREATE TABLE clazz (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(30) NOT NULL UNIQUE,
    room        VARCHAR(20) DEFAULT NULL,
    begin_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    master_id   INT DEFAULT NULL,
    subject     TINYINT NOT NULL,
    create_time TIMESTAMP DEFAULT NULL,
    update_time TIMESTAMP DEFAULT NULL
);

-- ========================================
-- student
-- ========================================
CREATE TABLE student (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    no              CHAR(10) NOT NULL UNIQUE,
    gender          TINYINT NOT NULL,
    phone           VARCHAR(11) NOT NULL UNIQUE,
    id_card         CHAR(18) NOT NULL UNIQUE,
    is_college      TINYINT NOT NULL,
    address         VARCHAR(100) DEFAULT NULL,
    degree          TINYINT DEFAULT NULL,
    graduation_date DATE DEFAULT NULL,
    clazz_id        INT NOT NULL,
    violation_count TINYINT NOT NULL DEFAULT 0,
    violation_score TINYINT NOT NULL DEFAULT 0,
    create_time     TIMESTAMP DEFAULT NULL,
    update_time     TIMESTAMP DEFAULT NULL,
    image           VARCHAR(255) DEFAULT NULL
);