spring:
  application:
    name: your-application-name
  datasource:
    url: your url
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your username
    password: your password
  servlet:
    multipart:
      # the max size of a single file
      max-file-size: 10MB
      # the max size of the request (including file and form data)
      max-request-size: 10MB

# MyBatis configurations
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # Enable CamelCase Naming Convention Mapping
    map-underscore-to-camel-case: true

# config the logging level of the transaction manager
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# Aliyun OSS configs
#
# the endpoint of the aliyun oss
# the bucket name of the aliyun oss
# the region of the aliyun oss
aliyun:
  oss:
    endpoint: https://oss-cn-huhehaote.aliyuncs.com
    bucketName: java-learn-noon
    region: cn-huhehaote

# JWT Token configs
jwt:
  # the secret of the jwt token
  secret: your jwt token secret
  # the expiration time of the jwt token (in seconds)
  expiration: 86400